#ifndef REPREPRO_GLOBALS_CONFIG_OPTION_OWNER_H
#define REPREPRO_GLOBALS_CONFIG_OPTION_OWNER_H

enum config_option_owner {
    CONFIG_OWNER_DEFAULT = 0,
    CONFIG_OWNER_FILE,
    CONFIG_OWNER_ENVIRONMENT,
    CONFIG_OWNER_CMDLINE
};

#endif
